gitlab:
  access-token: ${GITLAB_READ_API}
  project-ids: <COMMA SEPERATED GITLAB PROJECT IDS>
  pull-interval-minutes: 1

quarkus:
  banner:
    # generator: http://patorjk.com/software/taag/#p=display&f=Standard&t=vimon
    path: banner.txt
  tls:
    trust-all: true
  rest-client:
    gitlab-api:
      url: https://gitlab.com/api/v4
  http:
    cors:
      ~: true
      origins: "http://localhost:3000" #checkout ui git@github.com:enisbrulic/vimon-ui.git
      methods: "GET,OPTIONS"
